### ISSUE TITLE
Latest builds are failing

### ISSUE THREAD

**Issue by zuphilip** [kba/docker-ocropy#5]
The latest builds are failing, e.g. https://hub.docker.com/r/kbai/ocropy/builds/bqw69c2bajtq8ufiygcaf26/. It seems that models cannot be found from the `ocr-models` service on our server.

**Comment by kba** [comment]
Yeah, it crashed at some point, rebuilding now https://hub.docker.com/r/kbai/ocropy/builds/bbrd9jweiy6kyubl8sjymtn/

**Comment by kba** [comment]
Fixed.
